receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1000

exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: https://otel.kloudmate.dev:4318
    headers:
      Authorization: sk_Zt1rsTxryhipgPMkB2SCldrF

service:
  pipelines:
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlphttp, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]